apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: global
  namespace: ns-{{ .Values.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: global
  data:
  - secretKey: keystore-pass
    remoteRef:
      key: azure_k8s/environments/global
      property: keystore-password
  - secretKey: formio-jwt
    remoteRef:
      key: azure_k8s/environments/global
      property: formio-jwt-secret
  - secretKey: formio-admin-user
    remoteRef:
      key: azure_k8s/environments/{{ .Values.username }}
      property: formio-admin-user
  - secretKey: formio-admin-pass
    remoteRef:
      key: azure_k8s/environments/{{ .Values.username }}
      property: formio-admin-pass
  - secretKey: dp-proxy-inst-passwd
    remoteRef:
      key: azure_k8s/environments/{{ .Values.username }}
      property: connect-proxy-inst-passwd

##################################################################################
##################################################################################
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus
  namespace: ns-{{ .Values.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nexus-registry
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        ### WARNING. It's not allowed use this - only this _
        .dockerconfigjson: "{{ `{{ .registry }}` }}"
  data:
  - secretKey: registry
    remoteRef:
      key: azure_k8s/environments/global
      property: docker-config